/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exam;

/**
 *
 * @author RHYSTER
 */
public class frmDecrypt extends javax.swing.JFrame {
    Encrypt func = new Encrypt();
    FileReadWrite read = new FileReadWrite();

    /**
     * Creates new form frmDecrypt
     */
    public frmDecrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaM1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaK1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaE1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaM2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaM3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaK2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaE2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnE1 = new javax.swing.JButton();
        btnN1 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txdM1 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txdK1 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txdE1 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txdM2 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txdN1 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txdK2 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        txdE2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btndN1 = new javax.swing.JButton();
        btndE2 = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btndE1 = new javax.swing.JButton();

        txaM1.setColumns(20);
        txaM1.setRows(5);
        txaM1.setText("hutech");
        jScrollPane1.setViewportView(txaM1);

        txaK1.setColumns(20);
        txaK1.setRows(5);
        txaK1.setText("baomatthongtin");
        jScrollPane2.setViewportView(txaK1);

        txaE1.setColumns(20);
        txaE1.setRows(5);
        jScrollPane3.setViewportView(txaE1);

        txaM2.setColumns(20);
        txaM2.setRows(5);
        txaM2.setText("hutech");
        jScrollPane4.setViewportView(txaM2);

        txaM3.setColumns(20);
        txaM3.setRows(5);
        txaM3.setText("hutech");
        jScrollPane7.setViewportView(txaM3);

        txaK2.setColumns(20);
        txaK2.setRows(5);
        txaK2.setText("baomatthongtin");
        jScrollPane5.setViewportView(txaK2);

        txaE2.setColumns(20);
        txaE2.setRows(5);
        jScrollPane6.setViewportView(txaE2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ENCRYPT");

        btnE1.setText("Encrypt (M1)");

        btnN1.setText("Combine String (N1)");

        btnE2.setText("Encrypt (N1)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Message (M2):");

        jLabel2.setText("Message (M1):");

        jLabel6.setText("Key (K2):");

        jLabel3.setText("Key (K1):");

        jLabel7.setText("Cipher (E2):");

        jLabel4.setText("Message (E1):");

        jLabel8.setText("Message(N1):");

        txdM1.setEditable(false);
        txdM1.setColumns(20);
        txdM1.setRows(5);
        txdM1.setEnabled(false);
        jScrollPane8.setViewportView(txdM1);

        txdK1.setEditable(false);
        txdK1.setColumns(20);
        txdK1.setRows(5);
        txdK1.setEnabled(false);
        jScrollPane9.setViewportView(txdK1);

        txdE1.setEditable(false);
        txdE1.setColumns(20);
        txdE1.setRows(5);
        txdE1.setEnabled(false);
        jScrollPane10.setViewportView(txdE1);

        txdM2.setEditable(false);
        txdM2.setColumns(20);
        txdM2.setRows(5);
        txdM2.setEnabled(false);
        jScrollPane11.setViewportView(txdM2);

        txdN1.setEditable(false);
        txdN1.setColumns(20);
        txdN1.setRows(5);
        txdN1.setEnabled(false);
        jScrollPane12.setViewportView(txdN1);

        txdK2.setEditable(false);
        txdK2.setColumns(20);
        txdK2.setRows(5);
        txdK2.setEnabled(false);
        jScrollPane13.setViewportView(txdK2);

        txdE2.setEditable(false);
        txdE2.setColumns(20);
        txdE2.setRows(5);
        txdE2.setEnabled(false);
        jScrollPane14.setViewportView(txdE2);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("DECRYPT");

        btndN1.setText("Separate (N1) = E1 + M2");
        btndN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndN1ActionPerformed(evt);
            }
        });

        btndE2.setText("Decrypt (E2)");
        btndE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndE2ActionPerformed(evt);
            }
        });

        btnRead.setText("Read (E2)");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btndE1.setText("Decrypt (E1)");
        btndE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndE1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRead, btndE2, btndN1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane10, jScrollPane11, jScrollPane12, jScrollPane8, jScrollPane9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btndE2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btndN1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btndE1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        String E2 = read.readMessage();
        int K2 = read.readKey2();
        txdE2.setText(E2);
        txdK2.setText(String.valueOf(K2));
    }//GEN-LAST:event_btnReadActionPerformed

    private void btndE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndE2ActionPerformed
        // TODO add your handling code here:
        String E2 = txdE2.getText();
        int K2 = read.readKey2();
        String N1 = func.decRF(E2, K2);
        
        txdN1.setText(N1);
    }//GEN-LAST:event_btndE2ActionPerformed

    private void btndN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndN1ActionPerformed
        // TODO add your handling code here:
        String E1, M2;
        E1 = ""; M2 = "";
        String N1 = txdN1.getText();
        int lenE1 = read.readLen();
        int lenMess = N1.length();
        
        for (int i = 0; i < lenMess; i++) {
            if(i < lenE1){
                E1 += N1.charAt(i);
            }
            else{
                M2 += N1.charAt(i);
            }
        }
        
        txdE1.setText(E1);
        txdM2.setText(M2);
    }//GEN-LAST:event_btndN1ActionPerformed

    private void btndE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndE1ActionPerformed
        // TODO add your handling code here:
        String K1 = read.readKey1();
        String E1 = txdE1.getText();
        String M1 = func.decVig(E1, K1);
        
        txdK1.setText(K1);
        txdM1.setText(M1);
    }//GEN-LAST:event_btndE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDecrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE1;
    private javax.swing.JButton btnE2;
    private javax.swing.JButton btnN1;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btndE1;
    private javax.swing.JButton btndE2;
    private javax.swing.JButton btndN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea txaE1;
    private javax.swing.JTextArea txaE2;
    private javax.swing.JTextArea txaK1;
    private javax.swing.JTextArea txaK2;
    private javax.swing.JTextArea txaM1;
    private javax.swing.JTextArea txaM2;
    private javax.swing.JTextArea txaM3;
    private javax.swing.JTextArea txdE1;
    private javax.swing.JTextArea txdE2;
    private javax.swing.JTextArea txdK1;
    private javax.swing.JTextArea txdK2;
    private javax.swing.JTextArea txdM1;
    private javax.swing.JTextArea txdM2;
    private javax.swing.JTextArea txdN1;
    // End of variables declaration//GEN-END:variables
}
